name: Project CI
on:
  push:
    branches: ['main']

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: install-kubectl 
      run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - name: install-skaffold 
      run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/
    - name: check-kubectl
      run: kubectl version --client
    - name: check-skaffold
      run: skaffold version
    - name: ghcr-login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: checkout
      uses: actions/checkout@v3
    - name: skaffold-build
      run: skaffold build --default-repo=ghcr.io/jracollins

  

